// scripts/hash-assets.js
//
// Media (images, Lottie JSON, helper scripts) lives in big_assets/, outside src/ and static/, so Vite never bundles it.
// This script gives that folder a content hash, so the deployed folder is named _big_assets.<hash>/ and can be cached forever.
// The hash changes only when a media file changes, so a copy edit never re-uploads the media.
//
// Two steps, run by `npm run build`:
//   node scripts/hash-assets.js          BEFORE vite build: compute the hash, write src/lib/assets.js (ASSET_BASE)
//   node scripts/hash-assets.js --copy   AFTER vite build: copy big_assets/ to dist/_big_assets.<hash>/
//
// Why two steps (a change from the spec): adapter-static empties dist/ when it writes the build,
// so anything copied into dist/ before `vite build` would be deleted.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync, cpSync, existsSync, rmSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SRC = join(ROOT, 'big_assets');
const DIST = join(ROOT, 'dist');
const OUT_JS = join(ROOT, 'src/lib/assets.js');

/** Every file under a folder, sorted, skipping dotfiles (.gitkeep) so they don't affect the hash. */
function listFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir).sort()) {
    if (name.startsWith('.')) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...listFiles(full));
    else out.push(full);
  }
  return out;
}

/** One hash over every file's path and bytes: rename, add, remove or edit any file and the hash changes. */
function hashFolder(dir) {
  const h = createHash('sha256');
  for (const file of listFiles(dir)) {
    h.update(relative(dir, file).split(sep).join('/'));
    h.update(readFileSync(file));
  }
  return h.digest('hex').slice(0, 10);
}

const hash = hashFolder(SRC);
const folder = `_big_assets.${hash}`;
const files = listFiles(SRC);

if (process.argv.includes('--copy')) {
  if (!existsSync(DIST)) {
    console.error('dist/ not found. Run vite build first.');
    process.exit(1);
  }
  const target = join(DIST, folder);
  rmSync(target, { recursive: true, force: true });
  mkdirSync(target, { recursive: true });
  for (const file of files) {
    const dest = join(target, relative(SRC, file));
    mkdirSync(join(dest, '..'), { recursive: true });
    cpSync(file, dest);
  }
  console.log(`hash-assets: copied ${files.length} files to dist/${folder}/`);

  // Safety net: every media URL the prerendered page uses must exist in the copied folder.
  // (The prerender crawler skips these URLs because the folder doesn't exist yet when it runs.)
  const html = readFileSync(join(DIST, 'index.html'), 'utf8');
  const urls = new Set([...html.matchAll(/_big_assets\.([a-f0-9]+)\/([^"'\s)]+)/g)].map((m) => `${m[1]} ${m[2]}`));
  const used = [...urls].map((u) => u.split(' '));
  const missing = used.filter(([h, path]) => h !== hash || !existsSync(join(target, path)));
  if (missing.length) {
    console.error('hash-assets: index.html references media that is missing or from another hash:');
    for (const [h, path] of missing) console.error(`  _big_assets.${h}/${path}`);
    process.exit(1);
  }
  console.log(`hash-assets: verified ${used.length} media URLs in index.html`);
} else {
  // Dev serves the raw folder at /big_assets. Production points at the hashed folder, relative to index.html,
  // so the whole dist/ folder can live under any CDN path.
  const js = `// GENERATED by scripts/hash-assets.js. Do not edit by hand.
// Media base URL. Dev reads the raw big_assets/ folder; production reads the content-hashed copy next to index.html.
import { dev } from '$app/environment';

export const ASSET_HASH = '${hash}';
export const ASSET_BASE = dev ? '/big_assets' : './${folder}';

/** Build a media URL: asset('images/two-up-1.webp') */
export const asset = (path) => \`\${ASSET_BASE}/\${path}\`;
`;
  writeFileSync(OUT_JS, js);
  console.log(`hash-assets: ${files.length} files → ${folder} (wrote src/lib/assets.js)`);
}
