// GENERATED by ../birdkit-kit/hash-assets.js. Do not edit by hand.
// Media base URL. Dev reads the raw big_assets/ folder; production reads the content-hashed copy next to index.html.
import { dev } from '$app/environment';

export const ASSET_HASH = '577e3cf8f5';
export const ASSET_BASE = dev ? '/big_assets' : './_big_assets.577e3cf8f5';

/** Build a media URL: asset('images/two-up-1.webp') */
export const asset = (path) => `${ASSET_BASE}/${path}`;
